### PR TITLE
Change dependency of monofony/customer with sylius/customer

### LINKED ISSUE #92: Question
Hi, 

I was experimenting monofony. So when I ran 

```
composer create-project monofony/skeleton project_name
```

I came across a strange error.

```
Warning: Ambiguous class resolution, "Sylius\Component\Customer\Context\CustomerContextInterface" was found in both "/Users/harikt/projects/monofony-experiments/vendor/monofony/customer/Context/CustomerContextInterface.php" and "/Users/harikt/projects/monofony-experiments/vendor/sylius/customer/Context/CustomerContextInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Sylius\Component\Customer\Model\CustomerGroup" was found in both "/Users/harikt/projects/monofony-experiments/vendor/monofony/customer/Model/CustomerGroup.php" and "/Users/harikt/projects/monofony-experiments/vendor/sylius/customer/Model/CustomerGroup.php", the first will be used.
Warning: Ambiguous class resolution, "Sylius\Component\Customer\Model\Customer" was found in both "/Users/harikt/projects/monofony-experiments/vendor/monofony/customer/Model/Customer.php" and "/Users/harikt/projects/monofony-experiments/vendor/sylius/customer/Model/Customer.php", the first will be used.
Warning: Ambiguous class resolution, "Sylius\Component\Customer\Model\CustomerInterface" was found in both "/Users/harikt/projects/monofony-experiments/vendor/monofony/customer/Model/CustomerInterface.php" and "/Users/harikt/projects/monofony-experiments/vendor/sylius/customer/Model/CustomerInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Sylius\Component\Customer\Model\CustomerGroupInterface" was found in both "/Users/harikt/projects/monofony-experiments/vendor/monofony/customer/Model/CustomerGroupInterface.php" and "/Users/harikt/projects/monofony-experiments/vendor/sylius/customer/Model/CustomerGroupInterface.php", the first will be used.
Warning: Ambiguous class resolution, "Sylius\Component\Customer\Model\CustomerAwareInterface" was found in both "/Users/harikt/projects/monofony-experiments/vendor/monofony/customer/Model/CustomerAwareInterface.php" and "/Users/harikt/projects/monofony-experiments/vendor/sylius/customer/Model/CustomerAwareInterface.php", the first will be used.
```

Looking into this, I can see the `monofony/customer` is a fork of `sylius/customer` itself and namespaces are same. Any reason then why this package exists ?

You can reproduce the above via 

```
composer dumpautoload -o
```

### PR DESCRIPTION
**Pull request by harikt**
| Q               | A                                       |
|-----------------|-----------------------------------------|
| Branch?         | 0.11                            |
| Bug fix?        | yes                                  |
| New feature?    | no                                  |
| Related tickets | fixes [92](https://github.com/Monofony/Skeleton/issues/92) | [CoreContracts #1](https://github.com/Monofony/CoreContracts/pull/1) |
| License         | MIT                                     |

 - Bug fixes must be submitted against the 0.10 branch
 - Features and deprecations must be submitted against the 0.11 branch

Is the above statement true ?

### CODE REVIEW

**Comment by harikt** [comment]
@loic425 anything blocking to merge this PR ?

**Comment by loic425** [comment]
It seems perfect. I just need to fix the base branch first. I'll try to do that and merge your PR in the beginning of next week.

**Review by loic425 — APPROVED** [review]

**Comment by loic425** [comment]
@harikt Could you rebase your PR with 0.10 branch please? I've fixed the CI on bug fix branch.

**Comment by harikt** [comment]
I hope I did it correctly. Let me know in case of any other issues.

**Comment by loic425** [comment]
Thanks @harikt :tada:

**Pull request merged**
